services:
  app:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: "environments/.env"
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    depends_on:
      - database

  database:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    # env_file: "environments/.env"
    volumes:
      - mongodb_data:/data/db  # Этот volume сохраняет данные MongoDB

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@database:27017/

volumes:
  mongodb_data:  # Здесь определен volume для MongoDB
